### ISSUE TITLE
Why "menu button" in 2C?

### ISSUE THREAD

**Issue by JAWS-test** [w3c/accname#104]
In 2E a menu button is mentioned whose value should be used instead of its label. However, in my opinion, value and label are identical for buttons, so I would be in favor of removing the menu button in 2C.

Maybe a menu is meant instead of a menu button (see https://github.com/w3c/accname/issues/67). If this is the case, there would also be other controls whose value could be used with 2C, e.g. tablist, treeview, grid, radiogroup, etc.

**Comment by MelSumner** [comment]
Updated issue title and description due to re-ordering of steps.
