### ISSUE TITLE
2F - does name from content mean only name?

### ISSUE THREAD

**Issue by kengdoj** [w3c/accname#136]
In this example:

`<a href=”#”><img alt=”baby shark” title=”doo doo doo”></a>`

Would the link `<a>` have an accessible description? 

questions about the following instructions:

2F:  "if the current node's role allows [name from content](https://www.w3.org/TR/wai-aria/#namefromcontent)" 
    - does this mean _only_ name is allowed but description from content is not allowed?
    - or, if the role is on the list of name from content, then do i, ii, and iii. 

Related: 
2F.iii.b: "Compute the text alternative... " 
    - if description from content is not allowed, should this instruction be changed to "Compute the name"?

Thanks!

**Comment by JAWS-test** [comment]
If I understand this specification and https://www.w3.org/TR/html-aam-1.0/#accessible-name-and-description-computation correctly, an element only has a description if the description is explicitly declared on the element (e.g. per title, aria-description, aria-describedby, value)

The content is never used as a description with the following exceptions:
* if an element is referenced by aria-describedby, then the accessible name of that element is determined and that name is used as the description of the element referenced by aria-describedby.
* content of caption in tables, if caption is not used as Accessible Name
* content of summary in details, if summary is not used as Accessible Name

In my opinion, the determination of Accessible Name and Description is so different from each other that it would be better to treat them in 2 separate chapters

**Comment by kengdoj** [comment]
Thank you, @JAWS-test. I agree that the separate computation instructions would be clearer.
