### ISSUE TITLE
Permalinks in computations should NOT use specific numbering in the link (because the numbering will change)

### ISSUE THREAD

**Issue by cookiecrook** [w3c/accname#139]
The AccName computation permalinks to specific steps are unique to their current position in the list, rather than unique to the content of the list item. For example `step2B.ii.c`:

```html
<li id="step2B.ii.c">Append the <code>result</code>, with a space, to the <code>accumulated text</code>.</li>
```

I believe this should be changed, as we reorder or add items from time-to-time. Keeping these numbered permalinks would either break permalinking, or would result in confusing legacy hashes that don't match the number.

Instead, they should use a unique, somewhat human readable ID ref, such as:
```html
<li id="idref_append_space">Append the <code>result</code>, with a space, to the <code>accumulated text</code>.</li>
```
Then the link wouldn't need to change if reordering happened.

**Comment by jnurthen** [comment]
Thoughts from 8/19 Deep Dive - folks please edit this.
* Step 1 - Initialization
* Step 2 - Computation
* 2A - hiddenNotReferenced
* 2B -

**Comment by cookiecrook** [comment]
Open questions... (feel free to edit this comment too)

- Should the embedded comments and examples have names and IDs, too?
- Should IDs use camelCase, underscore_separation, or something else?

**Comment by cookiecrook** [comment]
> Append the result of each step above, with a space, to the total accumulated text.
> After all steps are completed, the total accumulated text is used as the accessible name or accessible description of the element that initiated the computation.

Should the text above be "Step 3"?

**Comment by cookiecrook** [comment]
Note: I also filed #141 and #143 as separate issues when reviewing this outline.

**Comment by cookiecrook** [comment]
I have completed a first pass proposal in @jnurthen's comment above. @jnurthen, @joanmarie, @accdc, and @aleventhal please review.

**Comment by accdc** [comment]
This seems logical to me. Do others have any opinions?

**Comment by cookiecrook** [comment]
Also we can change the legacy `id` attributes to `name` to prevent old permalinks from breaking.
