### ISSUE TITLE
Make a document about accessible name generation for different types of elements

### ISSUE THREAD

**Issue by ollie-iterators** [w3c/accname#147]
I think that it might be easier for people to understand how to compute accessible names if there was a way to separate the accessible name generation process into the different types of elements that are being tested (Ex: links, buttons, list elements, table elements, ...)

**Comment by scottaohara** [comment]
Hi @ollie-iterators, does HTML AAM's individual element name / desc steps help with what you are looking for? https://w3c.github.io/html-aam/#accessible-name-and-description-computation

or are you looking for something else here?

**Comment by JAWS-test** [comment]
I think it would be helpful to include a link to HTML AAM (and if available, other specifications that define it more precisely for their language, e.g. SVG AAM) in Accname

**Comment by pkra** [comment]
> I think it would be helpful to include a link to HTML AAM (and if available, other specifications that define it more precisely for their language, e.g. SVG AAM) in Accname

There's actually a link at 

https://github.com/w3c/accname/blob/79a20078e929cfcd25c92e3b50cb994c21b1b697/index.html#L328

but hardcoded as anchor.

**Comment by ollie-iterators** [comment]
It would be better if it could be more separated from the "algorithm defined in [Accessible Name and Description: Computation and API Mappings 1.1](https://w3c.github.io/accname/)"

**Comment by ollie-iterators** [comment]
Closing this issue to move it into html-aam
