### ISSUE TITLE
Investigate adding automated accname tests in wpt/webdriver

### ISSUE THREAD

**Issue by jnurthen** [w3c/accname#174]
all the accname tests should be able to be rewritten to use webdriver.

**Comment by MelSumner** [comment]
ok! @accdc let's schedule some time to get on the same page about this and come up with an action plan. 👍

**Comment by cookiecrook** [comment]
Implemented in Chromium and WebKit.

Gecko tracker: https://bugzilla.mozilla.org/show_bug.cgi?id=1788867

**Comment by cookiecrook** [comment]
Docs on running the WPT tests: https://github.com/web-platform-tests/wpt/blob/c478d0f4a1c3cd64a35b6f451679365dddbed8f5/README.md

**Comment by cookiecrook** [comment]
Taking assignment as this is likely to be part of the [InterOp 2023](https://wpt.fyi/interop-2023) Accessibility Investigation.

**Comment by cookiecrook** [comment]
FWIW, the Mac configuration steps on the WPT site didn't work for me, so here's my variant of what worked.

## Setting up a new Mac system to run WPT tests

1. In Terminal, make sure you're using the system variant of python3: `% which python3` should return `/usr/bin/python3`
2. Download and install [Safari Technology Preview](https://developer.apple.com/safari/technology-preview/).
3. Add the following to ~/.zprofile or wherever you define your shell path.
```
export PATH="$( xcrun python3 -m site --user-base )/bin:$PATH"
```
4. In Terminal, `cd` to a directory where you want the WPT source to live, then:
```
xcrun git clone https://github.com/web-platform-tests/wpt.git
xcrun pip3 install --user virtualenv
cd wpt
sudo /Applications/Safari\ Technology\ Preview.app/Contents/MacOS/safaridriver --enable
./wpt make-hosts-file | sudo tee -a /etc/hosts
```
Note: Watch out for double hyphens in CLI params. Depending on the text field you copy out of, autocorrect may convert them to en dashes (–) which can look identical in monospace. 
5. In Safari Tech Preview, select Settings… Advanced. "Show Develop menu in menu bar" then select Develop > Allow Remote Automation.
6. Attempt to run a single test from Terminal.
```
python3 ./wpt run --log-mach-level debug --log-mach - --webdriver-arg="--diagnose" safari /webdriver/tests/get_computed_label/get.py
```
You should get some percentage of passes and failures. The specific passes/failures should match the CI results on [WPT.fyi](https://wpt.fyi/results/webdriver/tests/get_computed_label/get.py?label=experimental&label=master&aligned) for the same test.

**Comment by cookiecrook** [comment]
testdriver extension PR here: https://github.com/web-platform-tests/wpt/pull/38758/files

**Comment by cookiecrook** [comment]
Once that lands, you should be able to do:
```
python3 ./wpt run --log-mach-level debug --log-mach - --webdriver-arg="--diagnose" safari /accname/basic.html
python3 ./wpt run --log-mach-level debug --log-mach - --webdriver-arg="--diagnose" safari /aria/role/basic.html
```

**Comment by cookiecrook** [comment]
It should work in Chromium, too. Gecko has the prerequisite webdriver support planned for the April/May timeframe.

**Comment by cookiecrook** [comment]
Firefox patch here: https://bugzilla.mozilla.org/show_bug.cgi?id=1585622#c21 🎉

**Comment by cookiecrook** [comment]
Work continues in the following:
- #190 

Should we close this AccName #174 issue as completed?

**Comment by cookiecrook** [comment]
I think this is done now... There are currently 382 AccName tests among the other [WPT Accessibility tests](https://wpt.fyi/results/?label=master&label=experimental&aligned&q=label%3Aaccessibility). Closing.
