### ISSUE TITLE
Discuss how to break up the computedlabel tests in wpt/accname (to verify AccName computation)

### ISSUE THREAD

**Issue by cookiecrook** [w3c/accname#190]
Discuss how to break up the automated computedlabel tests in wpt/accname to verify AccName computation related to [testdriver implementation](https://github.com/web-platform-tests/wpt/pull/38758).

See also the resource utilities in [wpt/wai-aria/scripts/aria-utils.js](https://github.com/web-platform-tests/wpt/blob/master/wai-aria/scripts/aria-utils.js) after [WPT PR #38925](https://github.com/web-platform-tests/wpt/pull/38925/files#diff-6870d82f11ff11cf7c7b544756cecfdac2046acbfe2fbb0640e6d415fbf99916) lands.

**Comment by cookiecrook** [comment]
@jaragunde I see you added [a lot of label tests to Chromium recently (video)](https://youtu.be/P0AXQ1B-tzA). I wanted to make sure you're aware that many of these can be run in WPT now. Please join the discussion with ARIA WG AccName meetings and/or watch the https://github.com/web-platform-tests/interop-2023-accessibility-testing/issues repo.

**Comment by spectranaut** [comment]
some links:

chromium accname tests: https://source.chromium.org/chromium/chromium/src/+/main:content/test/data/accessibility/accname/

wpt accname tests: https://github.com/web-platform-tests/wpt/tree/master/accname/manual

**Comment by cookiecrook** [comment]
@spectranaut I don't believe we should worry about the WPT _manual_ accname tests for this effort. Let's focus on the new automation capability.

**Comment by spectranaut** [comment]
heyy sorry I'm a bit confused, I really don't understand what you are asking.

You want to write tests for accname using the webdriver computedlabel, correct? For WPT?

So, we could start by transforming existing tests in chrome or the existing "manual" tests in WPT, but maybe you mean we should write them from scratch?

**Comment by cookiecrook** [comment]
@spectranaut wrote:
> transforming existing tests in chrome

This makes sense to me and is part of why I copied in @jaragunde.

> or the existing "manual" tests in WPT

I we should review those as a last step to check for edge cases we don't catch in the first round of automated testing.

But in general, I think we could aim for:
 - Some balance between a single gargantuan test file and the ~160 test files in the manual directory.
 - One or more files that test the "happy path" cases for the overall algorithm.
 - An edge cases directory (or file name prefix) for testing any of the label tests not include in the main accname computation "happy path" tests (some of the manual tests could be ported here)
 - Perhaps separate directories (or file name prefixes) for the more difficult to test scenarios, like web components or other shadow DOM examples, the CSS cascade for generated alt fallback, etc.
 
Then again, if there aren't any strong opinions, I'll just start adding tests in the format how they make the most sense to me.
