### ISSUE TITLE
Need whitespace consistency for `computedlabel` in WPT tests

### ISSUE THREAD

**Issue by cookiecrook** [w3c/accname#192]
Need whitespace trimming consistency for `computedlabel` in WPT tests.

I recalled that AccName trimmed whitespace in each step and once again at the end. However in [this WPT review comment](https://github.com/web-platform-tests/wpt/pull/39604#discussion_r1175709941), @spectranaut noted that it either never did, or has been changed to remove those requirements. I started digging and noticed there were many outstanding whitespace and trimming related issues in the [AccName WhiteSpace Project](https://github.com/w3c/accname/projects/1).

Until there is a required whitespace consistency in AccName, we've resolved to trim the whitespace before comparison in WPT, normalizing the testing result even if the implementations have minor differences. If there is a resolution to address trimming again in AccName, please file a related issue to cull this workaround from `/wai-aria/scripts/aria-util.js` in the WPT source. Thanks.

**Comment by cookiecrook** [comment]
I think this can be closed? Nothing to do here except wait for the [whitespace project](https://github.com/w3c/accname/projects/1#card-42288231) to complete.

**Comment by accdc** [comment]
I believe it can be closed since it will be resolved when the other project is completed.
