### ISSUE TITLE
Seeking clarity on name property with `div`

### ISSUE THREAD

**Issue by howard-e** [w3c/accname#202]
This relates to a new wpt test being added for [comp_tooltip](https://w3c.github.io/accname/#comp_tooltip), with https://github.com/web-platform-tests/wpt/pull/42093.

```html
<div title="label" data-expectedlabel="label" data-testname="div with text with tooltip label" class="ex">content</div>
```

@cookiecrook [review comment](https://github.com/web-platform-tests/wpt/pull/42093#discussion_r1336446479) states:

> This `div` test may be ambiguous since its role is undefined and should in theory be `""`, `generic`, or `none`, which don't support name from: `author` or `contents`. Adding `role="group"` should remove the ambiguity IIRC.

We're seeking clarity on if there is a spec ambiguity here.

**Comment by cookiecrook** [comment]
ARIA spec defines `Name From: prohibited` on both of those roles... 
So should new tests verify the "name" is "" (not "title" or "content")?

**Comment by jnurthen** [comment]
No. This is an authoring requirement not a user agent requirement. We deliberately have not made this a UA requirement to avoid [breaking the web](https://github.com/w3c/aria/issues/1487)

**Comment by cookiecrook** [comment]
I assume that means we should just continue to not test `computedlabel` on generics? Howard's test has been updated to avoid that (explicitly `role="group"` now), so there is nothing to be done, unless we want to document this decision somewhere in the WPT repo.

**Comment by cookiecrook** [comment]
I think we’re good without a WPT source change or comment. If ambiguities or bugs sneak back in to the tests, we can always fix them. @howard-e please Marge the related test when you are ready. Thanks!
