### ISSUE TITLE
`name` not allowed on a `li` element

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/accname#214]
Ref: https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fw3c.github.io%2Faccname%2F

The HTML checker complains that there is a `name` attribute on a `li` element. Can we use another method for this that passes the HTML validator?

**Comment by pkra** [comment]
They don't appear to be used for anything.

Looking at https://github.com/w3c/accname/commit/9c71070a9b28b11feb7e3e66b4242b53bc8fdb71, it seems like they were left in place by @cookiecrook during #186.  Maybe to facilitate review or perhaps historical value? In the latter case, we could add a `data-historical-` prefix.

**Comment by daniel-montalvo** [comment]
Thanks for this detailed explanation, @pkra 

If @cookiecrook  does not object, I'm happy to take this on. I am taking an overall pass at most of the ARIA modules to make them ready for transition to next maturity level.

**Comment by daniel-montalvo** [comment]
According to @jnurthen  this was left for old links to keep working. One can do https://github.io/accname/#step1 and be taken to the "Initialization" step under the "Text Equivalent Computation" section.

**Comment by pkra** [comment]
> According to @jnurthen this was left for old links to keep working. One can do https://github.io/accname/#step1 and be taken to the "Initialization" step under the "Text Equivalent Computation" section.

It doesn't though -- only for `a` tags. Putting the names on some anchors in the list items should work though.

**Comment by cookiecrook** [comment]
yes. we'll need to leave non-linked anchors: 

```html
<li id="newNamedStepID>
  <a name="oldNumberStepName">Labelledby:</a>
  etc etc
</li>

**Comment by cookiecrook** [comment]
Cool URIs don't change (or break)
https://www.w3.org/Provider/Style/URI

**Comment by cookiecrook** [comment]
@w3c/aria-editors Should there be a GitHub hook to include validation as a PR check?

**Comment by daniel-montalvo** [comment]
Not sure what we would check here in addition to what specprod already checks.

If you have a look at https://github.com/w3c/accname/actions/runs/6706842952 that is checking links and markup, including the HTML validator, which now fails on `<li name="">`

**Comment by cookiecrook** [comment]
Ah. I didn't know it was already validating. 

Now I'm wondering why that didn't get flagged on my original PR #186.

**Comment by daniel-montalvo** [comment]
@cookiecrook  We have a much lightweight set of linters for the PRs. I realized the other day because I wanted to make sure we could publish on TR, for winch markup validation and link checkers are compulsory.

**Comment by jnurthen** [comment]
We can't use `<a name>` as respec will try to resolve these as references

**Comment by cookiecrook** [comment]
> We can't use `<a name>` as respec will try to resolve these as references

Do you have another resolution in mind? I suppose we could drop the old permalinks.

**Comment by cookiecrook** [comment]
Oh I know. We can move the old numbered name to an `id` on the `<em>` that is the first child of each `li`

**Comment by jnurthen** [comment]
I created a PR with empty spans with IDs - see above. Seems to validate fine and works

**Comment by jnurthen** [comment]
> Oh I know. We can move the old numbered name to an `id` on the `\<em\>` that is the first child of each `li`
> 
> ```
> <li id="newNamedStepID">
>   <em id="oldNumberedStepName">Labelledby:</em>
>   etc etc

> The `\<em\>` should already be there... Just move the attr to the firstChild and change the attr name from `name` to `id`.

Not every line with the name attributes has an em element to add it to. Decided adding a span and being consistent was more important

**Comment by cookiecrook** [comment]
okay... let's continue in the PR
