### ISSUE TITLE
AccName computation: gap in computation 

### ISSUE THREAD

**Issue by anevins12** [w3c/accname#227]
# Description of bug or feature request

It appears that there's a gap in the accessible name computation where authors can implement form controls without accessible names. Please correct me if I'm wrong.

### A common scenario that falls through the name computation:
A programmatically associated form control `<label>` is hidden via CSS `visibility: hidden` or `display: none`. As a result, the form control has no accessible name.

```
<label for="control1" style="display: none"> Search </label>
<input id="control1" type="text" ... />
```

### A scenario that is caught by the name computation:
A programmatically associated form control `<label>` is hidden via CSS in the same way, but the label is referenced via `aria-labelledby`:
```
<label id="control1-name" style="display: none"> Search </label>
<input type="text" aria-labelledby="control1-name" ... />
```

**Comment by pkra** [comment]
Thanks for filing an issue. As discussed on today's WG call, closing this in favor of https://github.com/w3c/html-aam/issues/370.
