### ISSUE TITLE
Accname testable statements include prohibited name situations

### ISSUE THREAD

**Issue by aleventhal** [w3c/accname#241]
Tests 596-599 all expect the browser to return an accessible name on a generic div, even though name is prohibited in these cases. I think it's important to know that the name is prohibited on certain roles for reasons that affect end users. Some screen readers can't cope with the important text of a structural element being on the accessible name instead of in the contents.

This testable statement / expectation currently prevents Chrome from trying to repair the content, e.g. by moving the name to the description of the element.

Example of test:
https://www.w3.org/wiki/AccName_1.1_Testable_Statements#Name_test_case_597

@accdc @scottaohara WDYT?

**Comment by aleventhal** [comment]
Related: issue 240 which is for the comp_label WPT test.

**Comment by MelSumner** [comment]
Looking at the issue: 

ACCNAME spec should state what roles should not have a name. 

@aleventhal  Is this an accurate summation of your issue?

**Comment by aleventhal** [comment]
> ACCNAME spec should state what roles should not have a name.

I'm not really for or against that, but perhaps it would be redundant with ARIA.

My request is more that the testable statements be altered to not name plain divs, since that's prohibited, and perhaps the browser developer will want to explore repairs there (we are looking at it).

**Comment by MelSumner** [comment]
Okay, after digging a bit deeper...I don't think that wiki is accurate or should be used. I think WPT would be the source of truth now. 

@spectranaut @jnurthen could we consider deprecating that wiki? Perhaps adding a message that the wiki is deprecated and link to what folks should be looking at instead. WDYT?

**Comment by aleventhal** [comment]
That works for me. Thank you.

**Comment by spectranaut** [comment]
As discussed in the meeting, we are going to mark the wki as deprecated and point to the WPT tests for accname instead.
