### ISSUE TITLE
Input with multiple explicit label elements associated

### ISSUE THREAD

**Issue by giacomo-petri** [w3c/accname#249]
Related to this: https://github.com/w3c/accname/issues/108

What should happen if multiple `label` elements have the same `for` value?

Example:
```
<label for="test">This</label>
<label for="test">is</label>
<label for="test">a</label>
<label for="test">test</label>
<input type="text" id="test">
```
Browsers handle the calculation of the accessible name for the input inconsistently:
- Chrome concatenates the strings "This is a test"
- Safari uses only the first label, "This"
- Firefox concatenates the strings "This is a test"

The accessible name algorithm relies on the host language "_return that alternative in the form of a flat string as defined by the host language._" However, the host language is not clear on this, and browser behavior is inconsistent.

Should we address this inconsistency? Should we request that the HTML specifications clarify this?

Once a decision is made, it might be useful to create a WPT issue to test the behavior (I can take care of this).

**Comment by scottaohara** [comment]
This is defined in [html aam](https://www.w3.org/TR/html-aam-1.0/#input-type-text-input-type-password-input-type-number-input-type-search-input-type-tel-input-type-email-input-type-url-and-textarea-element-accessible-name-computation)

Otherwise use the associated label element or elements [accessible name(s)](https://www.w3.org/TR/accname-1.2/#dfn-accessible-name) - if more than one label is associated; concatenate by DOM order, delimited by spaces.

**Comment by giacomo-petri** [comment]
Thank you @scottaohara! I've missed it. Opening WPT if not already existing.

**Comment by scottaohara** [comment]
i "think" @adampage or @rahimabdi might have worked on wpts for this?  i might be wrong.  i can't check myself right now - but maybe look for PRs from them before starting up a new one?

**Comment by JAWS-test** [comment]
https://scottaohara.github.io/tests/html-inputs/double-label.html

**Comment by adampage** [comment]
> _i "think" @adampage or @rahimabdi might have worked on wpts for this? i might be wrong. i can't check myself right now - but maybe look for PRs from them before starting up a new one?_

Heya @scottaohara / @giacomo-petri — yep, I did write a PR that has coverage for this: web-platform-tests/wpt#44965

My goal was to test every piece of accname logic for [every element specified in HTML-AAM](https://www.w3.org/TR/html-aam-1.0/#accname-computation), so the PR is a monster. It introduces [510 subtests](https://wpt.fyi/results/html-aam/accname-computation-by-element?label=pr_head&max-count=1&pr=44965) with scattered failures across all 3 browsers.

> - _Chrome concatenates the strings "This is a test"_
> - <mark>_Safari uses only the first label, "This"_</mark>
> - _Firefox concatenates the strings "This is a test"_

@giacomo-petri — FWIW, Safari seems to conform to [the spec](https://www.w3.org/TR/html-aam-1.0/#accname-computation:~:text=name(s)%20%2D-,if%20more%20than%20one%20label%20is%20associated%3B%20concatenate%20by%20DOM%20order%2C%20delimited%20by%20spaces.,-If%20the%20accessible) now.

I manually confirmed [your code sample](https://codepen.io/adampage/pen/dPPpqmV/c6e44d0fedb62c530a6c6f326201368c) in Safari 18.4 ✅ , and [my latest WPT results](https://wpt.fyi/results/html-aam/accname-computation-by-element/inputs-with-placeholders.html?label=pr_head&max-count=1&pr=44965#:~:text=input%5Btype%3D%22text%22%5D%20expecting%20name%20from%202%20labels,PASS) also show a pass for all 3 browsers. ✅
