### ISSUE TITLE
A way to specify labelledby/describedy without requiring an id

### ISSUE THREAD

**Issue by jimmyfrasche** [w3c/accname#50]
(I realize that something like this is not the current priority and apologize if this is the wrong forum for such a proposal or if there exists such a mechanism that I am unaware of.)

Generating ids for `aria-labelledby` and `aria-describedby` can be difficult.

In a CMS it's not uncommon for two versions of a document to be rendered on a page from the same or similar templates. Consider the teaser for a blog entry listed in both "recent posts" in the sidebar and under "related content" in the footer of the current article. It's natural to code the teaser template similar to
```
<article aria-labelledby=blog-teaser-{{ id }}-title>
  <span id=blog-teaser-{{ id }}-title>{{ title }}</span>
  <!-- etc. -->
```
Simple, straightforward, and wrong. This template needs to know not just its content but it's context in order to generate a unique id. Worse, it's possible that the above works for many years until the "related content" section is added and it happens that an article is listed in both.

There are workarounds but they can be laborious or create their own problems. Even so, it assumes someone notices that there is a problem to work around.

I would like something like this:

```
<section aria-labelledby-child>
  <span aria-labels-parent><!-- etc. -->
```

An element with the `aria-labelledby-child` attribute computes its label from descendant elements marked `aria-labels-parent`.

The search for such children would need to end at a child that also has an `aria-labelledby-child`. That is, given
```
<section aria-labelledby-child>
  <span aria-labels-parent>A</span>
  <article aria-labelledby-child>
    <span aria-labels-parent>B</span>
  </article>
  <span aria-labels-parent>C</span>
</section>
```
The section is labelled "A C" and the article "B".

And similarly for `aria-describedby-child` and `aria-described-parent`.

There are, of course, still things that can go wrong, if one attribute is used without the other, but I believe it would solve more problems than it causes and be easier to get right in the common case.

While there are a lot of aria attributes that take an id, `aria-labelledby` and `aria-describedby` have some interesting commonalities:
- the label/description is almost always a descendant of what is being labeled/described (whether it is specified as the label/description or not)
- they are, in my experience, both
  - the most often used on a page
  - the least likely to be unique

Perhaps a more general mechanism is required, but something like the described fits my use cases and tracks with my experience.

**Comment by jnurthen** [comment]
While something like this would impact the accname spec it would fit in aria not accname. Any proposals which need new attributes would be better logged in the aria repository.
However, I think we are unlikely to go down this path as it would add more complexity to something that is already complex enough.

That being said we are looking at a few other possibilities for labeling. The current editors draft has 2 new ways of labeling a limited number of roles - see http://w3c.github.io/aria/#namecalculation and look for encapsulation and legend. Note that (a) this is not applicable across all roles and (b) it is not implemented anywhere yet.

**Comment by jimmyfrasche** [comment]
I'm reading that as:
- a direct descendant with `role=label` does the equivalent of `aria-labelledby`
- a direct descendant with `role=legend` does the equivalent of `aria-describedby`

And hence I could write
```html
<article>
  <div role=label><h2>Name of article</h2></div>
  <div role=legend>Description of article</div>
  stuff
</article>
```
instead of
```html
<article aria-labelledby=label aria-describedby=legend>
  <div id=label><h2>Name of article</h2></div>
  <div id=legend>Description of article</div>
  stuff
</article>
```

Is that correct? If so, that would certainly be good enough for me and I look forward to years of grousing about how no one supports it yet.

**Comment by jnurthen** [comment]
@jimmyfrasche No. This will only be allowed for certain roles which support these. Generally label will only work for widgets (like in HTML LABEL) and Legend for groups (like HTML fieldset).
There is also a proposal to allow a descendent Header to label something but it isn't advanced. See https://github.com/w3c/aria/issues/899 for more details although the minutes of the F2F meeting this week aren't yet in the issue.

**Comment by jimmyfrasche** [comment]
That's too bad. This only really presents an issue for stuff like `article`. Coming up with id's for forms isn't as fraught. It looks like the linked issue is the best place to discuss this further. Thank you for your time and help.
