### ISSUE TITLE
Output of child elements

### ISSUE THREAD

**Issue by JAWS-test** [w3c/accname#59]
If I understand it correctly, the AccName specification says nothing about the output of child elements when a parent element is labeled. This should be added. 
Example:
```
<nav aria-label=test>content</nav>
```
Here the text content in the region is output as soon as you navigate into the region.
```
<button aria-label=test>content</button>
```
Here the text content of the button is never output.

So the question is: For which elements are child elements not output?
One could assume that it applies to all elements whose children implicitly have role=presentation. But this is probably not true, because a link does not implicitly have role=presentation, but I would expect a link is output without its content, if it was labeled with aria-label or aria-labelledby.

See also: https://github.com/w3c/html-aam/issues/160#issuecomment-531088525

**Comment by scottaohara** [comment]
I think this is a good idea to call out, but would be better served as information in HTML AAM and the ARIA specifications specifically. 

accname defines how the accessible name is calculated, but the other specs should help define / advise how different elements and roles expect child content to be reached.

I'd recommend this issue be closed and taken up in the appropriate specs.

**Comment by JAWS-test** [comment]
Do you think I should post the ticket on ARIA and HTML AAM?

**Comment by scottaohara** [comment]
Not HTML AAM please.  There are already issues there (as you've already been commenting on) that cover this topic.

**Comment by JAWS-test** [comment]
@scottaohara: What HTML AAM issues do you mean? I can't find them

**Comment by scottaohara** [comment]
The HTML AAM issue you linked to here. It's related and we don't need a duplicate issue for it.
