### ISSUE TITLE
Do input fields in a  data table get their accessible names from headers?

### ISSUE THREAD

**Issue by devarshipant** [w3c/accname#86]
When a table header’s innertext is associated with the corresponding data cell, should the control get the accessible name of the table header’s innertext?

Both JAWS and NVDA speak the header when I tab to the form control. However, the forms list, in both screen readers, does not expose the name and neither does the accessibility tree.

See example: https://codepen.io/devpant/pen/XWXwYoJ

**Comment by accdc** [comment]
Hi,
In the case of screen readers like JAWS, the screen reader itself may change the feedback when it detects that a valid name is not applied, in which case it will guess based on the nearest text and announce that instead. This behavior though is not related to the AccName algorithm, which only applies when populating the accessibility tree.

So, if you see by examining the accessibility tree that there is no accessible name there, then the form field does not have a valid label according to the AccName algorithm.

You can fix this though, by setting aria-labelledby on the form field to reference the id of the container where the desired label is displayed, which will then populate the accessibility tree as expected.

Does this help?

All the best,
Bryan

**Comment by devarshipant** [comment]
Hi @accdc,

If we disregard the acc name calculation in this thread, it is unclear why the table header cannot be a label for a control in the data cell— will it be correct to say that a table header is programmatically associated with its respective data cell? 
We have a similar concept with the legend element where it serves as a programmatic label for every descendent control(s) in the fieldset.

Devarshi
